services:
  server:
    build:
      context: .
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
  db:
    image: postgres:17
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD?Variable not set}
      - POSTGRES_USER=${DB_USER?Variable not set}
      - POSTGRES_DB=${DB_DATABASE?Variable not set}
    expose:
      - 5432
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "$DB_DATABASE", "-U", "$DB_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env
volumes:
  db-data:
